variable "create" {
  type        = bool
  default     = true
  description = "Enable/disable the launch template."
}

variable "name" {
  type        = string
  default     = null
  description = <<EOT
    (Optional) The name of the launch template
    By default generated by Terraform. Conflicts with name_prefix.
  EOT
}

variable "name_prefix" {
  type        = string
  default     = null
  description = <<EOT
     (Optional) Creates a unique name beginning with the specified prefix.
     Conflicts with name.
  EOT
}

variable "description" {
  type        = string
  default     = null
  description = "Description of the launch template."
}

variable "default_version" {
  type        = number
  default     = null
  description = "Default Version of the launch template."
}

variable "update_default_version" {
  type        = bool
  default     = false
  description = <<EOT
    Whether to update Default Version each update. Conflicts with default_version.
  EOT
}

variable "block_device_mappings" {
  type        = list(any)
  default     = []
  description = "Configure additional volumes of the instance besides specified by the AMI."
}

#--------------------------------------
# Capacity reservation specification
#--------------------------------------
variable "capacity_reservation_preference" {
  type        = string
  default     = "none"
  description = <<EOT
    Indicates the instance's Capacity Reservation preferences.
    Can be open or none. (Default none).
  EOT
}

variable "capacity_reservation_id" {
  type        = string
  default     = null
  description = "The ID of the Capacity Reservation to target."
}
#--------------------------------------
variable "cpu_core_count" {
  type        = number
  default     = null
  description = "The number of CPU cores for the instance."
}

variable "cpu_threads_per_core" {
  type        = number
  default     = null
  description = "The number of CPU cores for the instance."
}

variable "cpu_credits" {
  type        = string
  default     = "standard"
  description = <<EOT
     The credit option for CPU usage. Can be "standard" or "unlimited".
     T3 instances are launched as unlimited by default.
     T2 instances are launched as standard by default.
  EOT
}

variable "elastic_gpu_type" {
  type        = string
  default     = null
  description = <<EOT
    The Elastic GPU Type
    https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/elastic-graphics.html#elastic-gpus-basics
  EOT
}

variable "elastic_inference_type" {
  type        = string
  default     = null
  description = <<EOT
    Attach an Elastic Inference Accelerator to the instance.
    https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-inference.html
  EOT
}

variable "enable_termination_protection" {
  type        = bool
  default     = false
  description = "If true, enables EC2 Instance Termination Protection."
}

variable "ebs_optimized" {
  type        = bool
  default     = false
  description = "If true, the launched EC2 instance will be EBS-optimized."
}

variable "iam_instance_profile_arn" {
  type        = string
  default     = null
  description = "The Amazon Resource Name (ARN) of the instance profile."
}

variable "iam_instance_profile_name" {
  type        = string
  default     = null
  description = "The name of the instance profile."
}

variable "ami_id" {
  type        = string
  default     = null
  description = "The AMI from which to launch the instance."
}

variable "instance_initiated_shutdown_behavior" {
  type        = string
  default     = "teminate"
  description = "Shutdown behavior for the instance. Can be stop or terminate."
}

#--------------------------------------
# SPOT market options
#--------------------------------------
variable "instance_market_options" {
  type        = map(string)
  default     = null
  description = <<EOT
   The market (purchasing) option for the instances.
   spot_block_duration_minutes - no longer available from July 1, 2021.
   spot_interruption_behavior = hibernate | stop | terminate
   spot_max_price = "" or a value
   spot_request_type = one-time | persistent
   spot_request_valid_until -  The end date of the spot request.
  EOT
}

#--------------------------------------

variable "instance_type" {
  type        = string
  default     = null
  description = "The type of the instance."
}

variable "kernel_id" {
  type        = string
  default     = null
  description = "The kernel ID."
}

variable "key_name" {
  type        = string
  default     = null
  description = "The key name to use for the instance."
}

variable "license_configuration_arns" {
  type        = list(string)
  default     = []
  description = "ARNs of the license configuration."
}
#--------------------------------------
# Metadata options
#--------------------------------------
variable "metadata_enable_service" {
  type        = bool
  default     = true
  description = "Whether the metadata service is available."
}

variable "metadata_require_http_token" {
  type        = bool
  default     = false
  description = "Whether or not the metadata service requires session tokens."
}

variable "metadata_response_hop_limit" {
  type        = number
  default     = 1
  description = <<EOT
    The desired HTTP PUT response hop limit for instance metadata requests.
    The larger the number, the further instance metadata requests can travel.
    Can be an integer from 1 to 64. (Default: 1).
  EOT
}
#--------------------------------------

variable "enable_monitoring" {
  type        = bool
  default     = false
  description = "If true, the launched EC2 instance will have detailed monitoring enabled."
}

variable "network_interfaces" {
  type        = list(any)
  default     = []
  description = "Attaches one or more Network Interfaces to the instance."
}

variable "placement" {
  type        = map(string)
  default     = null
  description = "The Placement Group of the instance."
}

variable "ram_disk_id" {
  type        = string
  default     = null
  description = "The ID of the RAM disk."
}

variable "security_group_ids" {
  type        = list(string)
  default     = null
  description = <<EOT
    A list of security group ids to associate with.
    If you are creating Instances in a VPC, use vpc_security_group_ids instead.
  EOT
}

variable "vpc_security_group_ids" {
  type        = list(string)
  default     = null
  description = <<EOT
    A list of security group IDs to associate with.
    Conflicts with network_interfaces.security_groups
  EOT
}

variable "tag_specifications" {
  type        = list(any)
  default     = []
  description = <<EOT
    The tags to apply to the resources during launch.
    You can tag instances, volumes, elastic GPUs and spot instance requests.
  EOT
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = <<EOT
    (Optional) A map of tags to assign to the launch template.
    If configured with a provider default_tags configuration block present,
    tags with matching keys will overwrite those defined at the provider-level.
  EOT
}

variable "user_data" {
  type        = string
  default     = null
  description = "The Base64-encoded user data to provide when launching the instance."
}

variable "enable_hibernation" {
  type        = bool
  default     = false
  description = "If set to true, the launched EC2 instance will hibernation enabled."
}

variable "enable_enclave" {
  type        = bool
  default     = false
  description = "(Optional) Enable Nitro Enclaves on launched instances."
}
