apiVersion: apps/v1
kind: Deployment
metadata:
  name: clubz-api
  namespace: clubz-dev
  labels:
    app: clubz-api
    purpose: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clubz-api
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: clubz-api
        purpose: api
    spec:
      containers:
        - name: clubz-api
          image: registry.digitalocean.com/clubz-platform-registry/clubz-api:latest
          imagePullPolicy: Always
          env:
            - name: ENV_NAME
              value: "dev"
            - name: DATABASE_NAME
              value: "defaultdb"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                 name: db-creds
                 key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                 name: db-creds
                 key: DATABASE_PASSWORD
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                 name: db-creds
                 key: DATABASE_HOST
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                 name: db-creds
                 key: DATABASE_URL
            - name: PORT
              value: "8000"
            - name: TZ
              value: "UTC"
            - name: AMQP_GAMES_EXCHANGE
              value: "games"
            - name: RMQ_HOST
              value: "rabbitmq-service.clubz-dev.svc.cluster.local"
            - name: RMQ_PORT
              value: "5672"
            - name: RMQ_VHOST
              value: "/"
            - name: RMQ_USER
              valueFrom:
                secretKeyRef:
                 name: rabbitmq
                 key: RMQ_USER
            - name: RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                 name: rabbitmq
                 key: RMQ_PASSWORD
            - name: RMQ_GAME_UPDATES_EXCHANGE
              value: "game_updates"
            - name: RMQ_FCM_EXCHANGE
              value: "fcm"
            - name: REDIS_ADDRESS
              value: "redis-service.clubz-dev.svc.cluster.local:6379"
            - name: REDIS_PASSWORD
              value: ""
            - name: REDIS_DB
              value: "0"
            - name: JWT_SECRET
              value: "your-jwt-secret-key-here"
            - name: ETHEREUM_CLIENT_URL
              value: ""
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi 