apiVersion: apps/v1
kind: Deployment
metadata:
  name: clubz-admin
  namespace: clubz-dev
  labels:
    app: clubz-admin
    purpose: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clubz-admin
  template:
    metadata:
      labels:
        app: clubz-admin
        purpose: admin
    spec:
      containers:
        - name: clubz-admin
          image: registry.digitalocean.com/clubz-platform-registry/clubz-admin:latest
          imagePullPolicy: Always
          args: ["server"]
          env:
            - name: DATABASE_NAME
              value: "defaultdb"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                 name: db-creds
                 key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                 name: db-creds
                 key: DATABASE_PASSWORD
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                 name: db-creds
                 key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                 name: db-creds
                 key: DATABASE_PORT

            - name: DJANGO_SECRET_KEY
              value: "your-django-secret-key-here"
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: DJANGO_SETTINGS_MODULE
              value: "mobile_api.settings"
            - name: AMQP_THROTTLING_ENABLED
              value: "True"
            - name: AMQP_THROTTLING_THRESHOLD
              value: "55"
            - name: AMQP_THROTTLING_SCHEDULE_INTERVAL
              value: "60"
            - name: AMQP_MATCH_EVENTS_EXCHANGE
              value: "match_events"
            - name: AMQP_GAMES_EXCHANGE
              value: "games"
            - name: AMQP_SYSTEM_EXCHANGE
              value: "system"
            - name: AMQP_NOTIFICATIONS_EXCHANGE
              value: "notifications"
            - name: RMQ_FCM_EXCHANGE
              value: "fcm"
            - name: RMQ_HOST
              value: "rabbitmq-service.clubz-dev.svc.cluster.local"
            - name: RMQ_PORT
              value: "5672"
            - name: RMQ_VHOST
              value: "/"
            - name: RMQ_USER
              valueFrom:
                secretKeyRef:
                 name: rabbitmq
                 key: RMQ_USER
            - name: RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                 name: rabbitmq
                 key: RMQ_PASSWORD
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: clubz-admin-service
  namespace: clubz-dev
spec:
  selector:
    app: clubz-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer 