services:
  rabbitmq-publisher:
    restart: "no"
    build:
      context: ../../clubz-rabbitmq-publisher
      dockerfile: ../clubz-rabbitmq-publisher/Dockerfile
    env_file:
      - .env.api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    # ports:
    #   - '${HOST_API_PORT}:${API_PORT}'
    # healthcheck:
    #   test: ["executable", "arg"]
    #   interval: 2s
    #   timeout: 3s
    #   retries: 10
    #   start_period: 3s
    volumes:
        - ../../clubz-rabbitmq-publisher:/app
  api-server:
    restart: "no"
    build:
      context: ../../clubz-api
      dockerfile: ../clubz-api/Dockerfile
    env_file:
      - .env.api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      rabbitmq-publisher:
        condition: service_started
    ports:
      - '${HOST_API_PORT}:${API_PORT}'
    volumes:
        - ../../clubz-api:/app